# file that contains the sample sheet
# If in doubt, just keep the default. But if you want to switch between
# alternative versions of your sample sheet, for example to test the
# workflow on a smaller subset of samples, you can change the file here.
sample_sheet: "config/samples.tsv"

aliases:
  # arbitrary string specifying the tumor alias
  # The value provided here needs to occur in the above specified sample_sheet,
  # indicating a tumor sample within a group of samples, where a group is
  # usually an individual.
  tumor: tumor
  # (optional) arbitrary string specifying the normal alias
  # This entry is optional, only provide it if you have a matched normal sample
  # for every tumor sample (same group entry in samples.tsv). If provided, the
  # workflow will run in tumor-normal mode. The value provided here needs to
  # occur in the above specified sample_sheet in the `alias` column.
  # If you only have a panel of normals that are not directly matched to your
  # tumor samples via the group column, specify the panel_of_normals alias
  # below and comment this entry out or leave it empty.
  matched_normal: normal
  # (optional) arbitrary string specifying the baseline alias
  # This entry is optional, only provide it if you don't have a matched normal
  # sample available for each tumor sample. All the samples in the sample_sheet
  # that have this panel_of_normals alias specified in the `alias` column, will
  # be used for the msisensor-pro baseline calculcation and the workflow will
  # then run in the tumor-only mode.
  # panel_of_normals: panel_of_normals

ref:
  # ensembl species name:
  # This species needs to be available for download via the Ensembl FTP site.
  # For a quick check, see the Ensembl species list:
  # https://www.ensembl.org/info/about/species.html
  # For full valid species names, consult the respective table for the release
  # you specify, for example for ‘114’ this is at:
  # https://ftp.ensembl.org/pub/release-114/species_EnsemblVertebrates.txt
  # And to browse available downloads in more detail, see the FTP server:
  # https://ftp.ensembl.org/pub/
  species: homo_sapiens
  # ensembl release version:
  # Update this to the latest working version, when you first set up a new
  # analysis on a dataset. Later, it only makes sense to update (or downgrade)
  # the release versions if either (a) the version you are using consistently
  # fails to download (some Ensembl release versions are just broken) or
  # (b) you know that a newer version will include changes that will fix some
  # error or adds transcripts that will be relevant to your analysis.
  release: 114
  # genome build:
  # Usually, this should just be the main build listed in:
  # https://ftp.ensembl.org/pub/release-114/species_EnsemblVertebrates.txt
  # For example, for homo_sapiens, you strip the assembly column entry
  # "GRCh38.p12" down to "GRCh38". If in doubt, navigate to the respective
  # cdna folder on the FTP server, and look for the correct build in the
  # file names there. For example "GRCh38" in:
  # https://ftp.ensembl.org/pub/release-114/fasta/homo_sapiens/cdna/
  build: GRCh38
